const GAMES={
  king:{name:'王者荣耀',short:'HONOR OF KINGS',accent:'#ffcf5c',source:'腾讯游戏官网 / 王者荣耀',sourceUrl:'https://pvp.qq.com/',gallery:[
    'https://static.gametalk.qq.com/image/18/1758621859_8a20d7d69f3e1b5215c7599f821d6a6d.jpg',
    'https://static.gametalk.qq.com/image/18/1758621870_4e762e2130e106e33efc6a087b4068db.jpg',
    'https://static.gametalk.qq.com/image/18/1758621882_db0e7da404a76821c9941fee28345feb.jpg',
    'https://static.gametalk.qq.com/image/18/1758621892_c58c9504f9bfefdacbd9bdede7aa63a4.jpg',
    'https://game.gtimg.cn/images/yxzj/coming/v2/skins//image/20250124/17376886142113.jpg',
    'https://game.gtimg.cn/images/yxzj/coming/v2/skins//image/20250123/17376016329335.gif'
  ]},
  naruto:{name:'火影忍者手游',short:'NARUTO MOBILE',accent:'#ff734e',source:'火影忍者手游官网 / 情报参考',sourceUrl:'https://hyrz.qq.com/',gallery:[
    'https://ossweb-img.qq.com/upload/webplat/info/hyrz/201607/1469087904_1436653066_28992_imageAddr.jpg',
    'https://ossweb-img.qq.com/upload/webplat/info/hyrz/201605/1463622866_1436653066_2786_imageAddr.jpg',
    'https://ossweb-img.qq.com/upload/webplat/info/hyrz/201605/1463622967_1436653066_13235_imageAddr.jpg',
    'https://ossweb-img.qq.com/upload/webplat/info/hyrz/201605/1463622835_1436653066_2222_imageAddr.jpg',
    'https://game.gtimg.cn/images/hyrzol/act/a20180411reserve/img/p1.jpg',
    'https://ossweb-img.qq.com/upload/webplat/info/hyrz/201607/1469087997_1436653066_31739_imageAddr.jpg'
  ]}
};
const BILIBILI_SOURCES={king:'https://space.bilibili.com/57863910',naruto:'https://space.bilibili.com/441897078'};
const INTEL={
  king:[
    {title:'十周年共创之夜',desc:'主视觉 / 节点传播',url:BILIBILI_SOURCES.king,img:0},
    {title:'嘉年华 / 城市活动',desc:'事件营销 / 社区话题',url:BILIBILI_SOURCES.king,img:2},
    {title:'新皮肤视觉',desc:'角色资产 / 宣发素材',url:GAMES.king.sourceUrl,img:4},
    {title:'版本内容观察',desc:'内容节奏 / 卖点拆解',url:BILIBILI_SOURCES.king,img:3}
  ],
  naruto:[
    {title:'忍者主题视觉',desc:'角色视觉 / 版本传播',url:BILIBILI_SOURCES.naruto,img:0},
    {title:'角色情报',desc:'人物内容 / 信息卖点',url:BILIBILI_SOURCES.naruto,img:1},
    {title:'忍者内容',desc:'角色内容 / 传播素材',url:BILIBILI_SOURCES.naruto,img:2},
    {title:'赛事视觉',desc:'赛事节点 / 高峰传播',url:BILIBILI_SOURCES.naruto,img:3}
  ]
};
const NODES=[['新内容上线','NEW CONTENT'],['新皮肤 / 商品','MONETIZATION'],['新玩法上线','NEW MODE'],['版本周年节点','ANNIVERSARY'],['电竞赛事节点','ESPORTS']];
const GOALS=['拉新','回流','活跃','社区热度'];
const AUDIENCE=['潜在新用户','流失玩家','核心玩家','泛活跃玩家'];
const CHANNELS=[
  {id:'douyin',name:'抖音',en:'DOUYIN',fit:92,cost:18},
  {id:'bilibili',name:'B站',en:'BILIBILI',fit:88,cost:16},
  {id:'redbook',name:'小红书',en:'REDNOTE',fit:78,cost:12},
  {id:'weibo',name:'微博',en:'WEIBO',fit:74,cost:10},
  {id:'community',name:'游戏社区',en:'COMMUNITY',fit:84,cost:7},
  {id:'live',name:'直播 / 赛事',en:'LIVE',fit:91,cost:22}
];
const ASSETS=[
 {id:'pv',code:'HERO PV',name:'版本主视觉 / PV',desc:'建立版本第一记忆点',kind:'认知',weight:3,cost:22,tag:'AWARENESS'},
 {id:'short',code:'15S SHORT',name:'15秒短视频',desc:'3秒 Hook + 单一卖点',kind:'认知',weight:1,cost:8,tag:'AWARENESS'},
 {id:'guide',code:'GUIDE',name:'玩法 / 攻略',desc:'解决“怎么玩”',kind:'互动',weight:1,cost:7,tag:'ENGAGE'},
 {id:'ugc',code:'UGC',name:'UGC 挑战 / 话题',desc:'让玩家参与传播',kind:'互动',weight:2,cost:12,tag:'ENGAGE'},
 {id:'kol',code:'KOL',name:'KOL / 主播联动',desc:'放大站外触达',kind:'认知',weight:2,cost:18,tag:'AMPLIFY'},
 {id:'live',code:'LIVE',name:'直播 / 赛事节点',desc:'集中制造传播高峰',kind:'互动',weight:3,cost:22,tag:'PEAK'},
 {id:'reward',code:'RETURN',name:'回流 / 福利提醒',desc:'推动存量用户行动',kind:'转化',weight:2,cost:10,tag:'CONVERT'},
 {id:'community',code:'COMMUNITY',name:'社区答疑 / 精选',desc:'承接玩家反馈',kind:'社区',weight:1,cost:7,tag:'COMMUNITY'},
 {id:'push',code:'PUSH',name:'站内触达 / Push',desc:'低成本触达存量',kind:'转化',weight:1,cost:3,tag:'CONVERT'},
 {id:'recap',code:'RECAP',name:'数据复盘 / 赛后卡',desc:'沉淀下一轮动作',kind:'复盘',weight:1,cost:4,tag:'LEARN'}
];
const DAYS=7,SLOTS=3,SLOT_NAMES=['AM','PM','NIGHT'];
const RESOURCE_LEVELS=[{name:'LEAN',points:70},{name:'MEDIUM',points:105},{name:'FULL',points:145}];
const state={game:'king',node:0,goal:'拉新',audience:'潜在新用户',resource:2,channelBudget:70,selectedChannels:['douyin','bilibili','community'],channelBudgets:{douyin:26,bilibili:22,community:22},board:Array.from({length:DAYS},()=>Array(SLOTS).fill(null)),picked:null,baselineScore:0,dragId:null,currentPage:'brief'};
const $=id=>document.getElementById(id);const flat=()=>state.board.flat().filter(Boolean);const assetById=id=>ASSETS.find(a=>a.id===id);
function imgFor(gameId,key='default'){const list=GAMES[gameId].gallery;let n=0;for(const ch of String(key))n=(n+ch.charCodeAt(0)*17)%997;return list[n%list.length]}
function usageText(a){return {认知:'建立记忆点',互动:'推动参与',转化:'推动行动',社区:'承接反馈',复盘:'沉淀学习'}[a.kind]||'支持执行'}
function strategy(){const map={拉新:{primary:['pv','short','kol'],support:['guide','ugc'],cta:['push'],main:'先解决“看见并记住”，再承接首次参与。'},回流:{primary:['reward','push','short'],support:['guide','community'],cta:['pv'],main:'先回答“为什么现在回来”，再给低门槛行动。'},活跃:{primary:['short','guide','ugc'],support:['live','push'],cta:['community'],main:'制造连续内容与任务节奏，让用户每天有理由回来。'},社区热度:{primary:['ugc','live','community'],support:['short','guide'],cta:['recap'],main:'先制造可讨论事件，再把讨论沉淀到社区。'}};const s=map[state.goal];return {...s,node:NODES[state.node][0],aud:state.audience,game:GAMES[state.game].name}}
function initNav(){document.querySelectorAll('.nav-item').forEach(btn=>btn.onclick=()=>goPage(btn.dataset.page));document.querySelectorAll('.next-page').forEach(btn=>btn.onclick=()=>goPage(btn.dataset.pageTarget));document.querySelectorAll('.nav-item').forEach(btn=>btn.addEventListener('click',()=>document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x===btn))))}
function goPage(page){state.currentPage=page;document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===`page-${page}`));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const labels={brief:'MISSION / SETUP',board:'CAMPAIGN BOARD / 7-DAY',mix:'MEDIA & CREATIVE / MIX',qa:'QA & DATA / REVIEW'};$('crumb').textContent=labels[page]||page;window.scrollTo({top:0,behavior:'smooth'});if(page==='qa')renderQA()}
function renderHero(){const g=GAMES[state.game];$('missionVisual').style.setProperty('--mission-img',`url("${g.gallery[0]}")`);$('missionVisual').innerHTML=`<div class="visual-tag"><small>${g.name}</small><b>${g.short}</b></div>`;$('mixGameTitle').textContent=g.name}
function renderGames(){$('gamePicker').innerHTML=Object.entries(GAMES).map(([id,g])=>`<button class="game-btn ${id===state.game?'active':''}" data-game="${id}"><img src="${g.gallery[0]}" alt=""><span><b>${g.name}</b><small>${g.short}</small></span><i></i></button>`).join('');$('gamePicker').onclick=e=>{const b=e.target.closest('[data-game]');if(!b)return;state.game=b.dataset.game;renderAll();toast(`已切换：${GAMES[state.game].name}`)}}
function renderNodes(){$('nodePicker').innerHTML=NODES.map((n,i)=>`<button class="stack-btn ${i===state.node?'active':''}" data-node="${i}"><b>${n[0]}</b><small>${n[1]}</small></button>`).join('');$('nodePicker').onclick=e=>{const b=e.target.closest('[data-node]');if(!b)return;state.node=+b.dataset.node;renderNodes();renderMissionBrief();renderInsight()}}
function renderGoals(){$('goalPicker').innerHTML=GOALS.map(x=>`<button class="chip ${x===state.goal?'active':''}" data-goal="${x}">${x}</button>`).join('');$('goalPicker').onclick=e=>{const b=e.target.closest('[data-goal]');if(!b)return;state.goal=b.dataset.goal;renderGoals();renderMissionBrief();renderInsight()}}
function renderAudience(){$('audiencePicker').innerHTML=AUDIENCE.map(x=>`<button class="chip ${x===state.audience?'active':''}" data-aud="${x}">${x}</button>`).join('');$('audiencePicker').onclick=e=>{const b=e.target.closest('[data-aud]');if(!b)return;state.audience=b.dataset.aud;renderAudience();renderMissionBrief();renderInsight()}}
function renderMissionBrief(){$('missionGame').textContent=GAMES[state.game].name;$('missionNode').textContent=NODES[state.node][0];$('missionGoal').textContent=state.goal;$('missionAudience').textContent=state.audience;$('resourceText').textContent=`${RESOURCE_LEVELS[state.resource-1].name} · ${RESOURCE_LEVELS[state.resource-1].points}R`;$('resourceCap').textContent=RESOURCE_LEVELS[state.resource-1].points}
function updateResource(){renderMissionBrief();const cap=RESOURCE_LEVELS[state.resource-1].points,used=flat().reduce((n,x)=>n+x.cost,0);$('resourceUsed').textContent=used;$('resourceBar').style.width=`${Math.min(100,used/cap*100)}%`}
function renderBoard(){const bank=`<div class="asset-bank">${ASSETS.map(a=>{const used=flat().filter(x=>x.id===a.id).length;return `<div class="asset-card ${state.picked===a.id?'picked':''}" draggable="true" data-asset="${a.id}"><div class="asset-art" style="--game-img:url('${imgFor(state.game,a.id)}')"></div><span class="code">${a.code}</span><b>${a.name}</b><small>${a.desc}</small><em>LOAD ${a.weight} · COST ${a.cost}${used?` · USED ${used}`:''}</em></div>`}).join('')}</div>`;let cols='';for(let d=0;d<DAYS;d++){const load=state.board[d].filter(Boolean).reduce((n,x)=>n+x.weight,0);cols+=`<div class="day-column ${load>5?'overload':''}" data-day="${d}"><div class="day-meta"><b>DAY ${String(d+1).padStart(2,'0')}</b><span>${load} LOAD</span></div>${Array.from({length:SLOTS},(_,s)=>{const x=state.board[d][s];return `<div class="slot ${x?'filled':''}" data-day="${d}" data-slot="${s}"><span class="slot-tag">${SLOT_NAMES[s]}</span>${x?`<div class="placed"><div class="mini-thumb" style="--game-img:url('${imgFor(state.game,x.id+'-mini')}')"></div><span class="tag">${x.tag}</span><b>${x.name}</b><small>${x.kind} · W${x.weight} · ${x.cost}R</small><button class="remove" data-remove="1">×</button></div>`:`<div class="slot-empty">DROP / CLICK</div>`}</div>`}).join('')}</div>`} $('board').innerHTML=bank+cols;const bankCards=document.querySelectorAll('.asset-card');bankCards.forEach(card=>{card.onclick=()=>{state.picked=card.dataset.asset;renderBoard();toast('已选择素材：点击日期槽位放置')};card.ondragstart=e=>{state.dragId=card.dataset.asset;e.dataTransfer.effectAllowed='copy';e.dataTransfer.setData('text/plain',state.dragId)}});document.querySelectorAll('.slot').forEach(slot=>{slot.ondragover=e=>{e.preventDefault();slot.classList.add('over')};slot.ondragleave=()=>slot.classList.remove('over');slot.ondrop=e=>{e.preventDefault();slot.classList.remove('over');place(+slot.dataset.day,+slot.dataset.slot,e.dataTransfer.getData('text/plain')||state.dragId)};slot.onclick=()=>{const d=+slot.dataset.day,s=+slot.dataset.slot;if(state.picked){place(d,s,state.picked);state.picked=null}else if(state.board[d][s])openAssetModal(state.board[d][s].id)}});document.querySelectorAll('[data-remove]').forEach(btn=>btn.onclick=e=>{e.stopPropagation();const slot=e.target.closest('.slot');state.board[+slot.dataset.day][+slot.dataset.slot]=null;renderBoard();refreshOps();toast('动作已移除')});renderBoardMeta()}
function place(d,s,id){const x=assetById(id);if(!x)return;const old=state.board[d][s];const cap=RESOURCE_LEVELS[state.resource-1].points;const current=flat().reduce((n,a)=>n+a.cost,0);const next=current-(old?old.cost:0)+x.cost;if(next>cap)return toast(`资源不足：当前上限 ${cap}R`);state.board[d][s]=x;renderBoard();refreshOps();toast(`已放置：${x.name}`)}
function renderBoardMeta(){const a=flat(),heavy=a.filter(x=>x.weight===3).length,days=new Set(state.board.map((d,i)=>d.some(Boolean)?i:null).filter(x=>x!==null)).size;const used=a.reduce((n,x)=>n+x.cost,0);$('boardKpis').innerHTML=[['ACTIONS',a.length,'PLACED'],['HEAVY',heavy,heavy>4?'HIGH LOAD':'CONTROLLED'],['ACTIVE DAYS',days,'/ 7 DAYS'],['RESOURCE',`${used}R`,`${RESOURCE_LEVELS[state.resource-1].points}R CAP`]].map(k=>`<div class="kpi-card"><small>${k[0]}</small><b>${k[1]}</b><em>${k[2]}</em></div>`).join('')}
function calcScore(){const c=getScoreComponents();return Math.max(0,Math.min(100,Math.round(c.goal*.32+c.coverage*.22+c.cadence*.18+c.channel*.12+c.resource*.1+c.budget*.06)))}
function getScoreComponents(){const a=flat(),s=strategy();if(!a.length)return{goal:0,coverage:0,cadence:0,channel:Math.round(state.selectedChannels.length/4*100),resource:70,budget:60};const goalCount=a.filter(x=>[...s.primary,...s.support,...s.cta].includes(x.id)).length;const goal=Math.min(100,goalCount/5*100);const coverage=Math.min(100,new Set(a.map(x=>x.kind)).size/4*100);const load=state.board.map(d=>d.filter(Boolean).reduce((n,x)=>n+x.weight,0));const over=load.filter(n=>n>5).length;const repeats=state.board.filter(d=>new Set(d.filter(Boolean).map(x=>x.kind)).size===1&&d.filter(Boolean).length>=2).length;const cadence=Math.max(0,100-over*18-repeats*6);const channel=Math.min(100,state.selectedChannels.length/4*100);const used=a.reduce((n,x)=>n+x.cost,0),cap=RESOURCE_LEVELS[state.resource-1].points;const resource=Math.max(0,Math.round(100-Math.max(0,used-cap*.75)/cap*100));const bUsed=state.selectedChannels.reduce((n,id)=>n+(state.channelBudgets[id]||0),0),budget=Math.max(0,100-Math.abs(state.channelBudget-bUsed)*2);return{goal,coverage,cadence,channel,resource,budget}}
function getIssues(){const a=flat(),out=[];if(!a.length)return[{level:'warn',text:'当前没有排期动作。拖入素材或生成基准方案。'}];if(!a.some(x=>x.kind==='认知'))out.push({level:'warn',text:'缺少认知动作：建议加入 PV / 短视频。'});if(!a.some(x=>x.kind==='互动'))out.push({level:'warn',text:'缺少互动动作：攻略、UGC 或直播至少需要一种。'});if(!a.some(x=>x.kind==='转化'))out.push({level:'warn',text:'缺少转化动作：回流 / Push 需要承担行为承接。'});state.board.forEach((d,i)=>{const load=d.filter(Boolean).reduce((n,x)=>n+x.weight,0);if(load>5)out.push({level:'bad',text:`Day ${String(i+1).padStart(2,'0')} 负载 ${load}，重资产堆叠。`});else if(load===5)out.push({level:'warn',text:`Day ${String(i+1).padStart(2,'0')} 接近负载上限。`});const kinds=d.filter(Boolean).map(x=>x.kind);if(kinds.length>=2&&new Set(kinds).size===1)out.push({level:'warn',text:`Day ${i+1} 同类型动作重复，内容节奏偏单一。`})});const used=a.reduce((n,x)=>n+x.cost,0),cap=RESOURCE_LEVELS[state.resource-1].points;if(used>cap*.92)out.push({level:'bad',text:`资源使用 ${used}/${cap}R，剩余空间过小。`});if(state.goal==='回流'&&!state.board.slice(0,4).flat().some(x=>x?.kind==='转化'))out.push({level:'bad',text:'回流目标前4天缺少转化动作。'});return out.slice(0,6)}
function getNextAction(){const a=flat(),issues=getIssues();if(!a.length)return{title:'GENERATE BASELINE',reason:'先生成一套可编辑的基础发行节奏。'};if(issues.some(x=>x.level==='bad'))return{title:'FIX CONFLICT',reason:'先处理红色冲突，再追求更高策略分。'};if(!a.some(x=>x.kind==='转化'))return{title:'ADD CONVERSION',reason:'加入回流 / Push，避免只做曝光。'};if(getScoreComponents().cadence<72)return{title:'BALANCE CADENCE',reason:'把重资产分散到不同日期。'};return{title:'RUN QA',reason:'当前结构可以进入人工微调。'}}
function renderInsight(){const s=strategy(),score=calcScore(),delta=state.baselineScore?score-state.baselineScore:0;$('insightHero').style.backgroundImage=`linear-gradient(90deg,rgba(5,7,9,.85),transparent 70%),url('${imgFor(state.game,s.node+'-'+state.goal)}')`;$('scoreValue').textContent=score;$('ringValue').textContent=score;$('scoreRing').style.setProperty('--score',score);$('scoreDelta').textContent=state.baselineScore?(delta>0?`+${delta}`:delta):'BASE';$('scoreLabel').textContent=score>=88?'EXECUTION READY':score>=74?'GOOD BASELINE':score>=55?'NEEDS TUNING':'BUILD A PLAN';$('scoreDesc').textContent=score>=88?'结构完整，节奏、资源和渠道匹配度较高。':score>=74?'骨架完整，可以通过微调提高效率。':score>=55?'目标覆盖不错，但资源或节奏存在浪费。':'先生成基准方案，再开始拖拽编辑。';renderCoverage();updateResource();}
function renderCoverage(){const arr=['认知','互动','转化','社区'];const max={认知:12,互动:10,转化:8,社区:6};$('coverage').innerHTML=arr.map(k=>{const val=flat().filter(x=>x.kind===k).reduce((n,x)=>n+x.weight,0);const p=Math.min(100,Math.round(val/max[k]*100));return `<div class="cov-row"><span>${k}</span><div class="bar"><i style="width:${p}%"></i></div><em>${p}</em></div>`}).join('');const issues=getIssues();$('issueBox').innerHTML=issues.map(i=>`<div class="issue-item ${i.level}">${i.text}</div>`).join('')||'<div class="issue-item ok">当前没有明显结构问题。</div>';const next=getNextAction();$('nextAction').textContent=next.title;$('nextReason').textContent=next.reason}
function renderChannels(){const g=GAMES[state.game];$('channelMix').innerHTML=CHANNELS.map(c=>{const selected=state.selectedChannels.includes(c.id),val=state.channelBudgets[c.id]||0;return `<div class="channel-card ${selected?'selected':''}" data-channel="${c.id}"><span class="channel-fit">FIT ${c.fit}</span><div class="channel-art" style="--game-img:url('${imgFor(state.game,c.id+'-channel')}')"></div><div class="channel-head"><b>${c.name}</b><small>${c.en}</small></div>${selected?`<div class="budget-line"><span>BUD</span><input data-budget="${c.id}" type="range" min="0" max="40" step="1" value="${val}"><b>${val}R</b></div>`:''}</div>`}).join('');document.querySelectorAll('.channel-card').forEach(card=>card.onclick=e=>{if(e.target.matches('input'))return;const id=card.dataset.channel;if(state.selectedChannels.includes(id)){state.selectedChannels=state.selectedChannels.filter(x=>x!==id)}else{if(state.selectedChannels.length>=4)return toast('最多选择 4 个渠道');state.selectedChannels.push(id);state.channelBudgets[id]=Math.min(20,CHANNELS.find(c=>c.id===id).cost)}rebalanceChannelBudgets();renderChannels();renderInsight()});document.querySelectorAll('[data-budget]').forEach(inp=>inp.oninput=e=>{state.channelBudgets[e.target.dataset.budget]=+e.target.value;renderChannels();renderInsight()});const bUsed=state.selectedChannels.reduce((n,id)=>n+(state.channelBudgets[id]||0),0);$('channelBudgetUsed').textContent=`${bUsed}R / ${state.channelBudget}R`;const diversity=Math.round(state.selectedChannels.length/4*100);$('diversityValue').textContent=`${diversity}%`;$('diversityBar').style.width=`${diversity}%`;updateMixCopy()}
function rebalanceChannelBudgets(){const total=state.channelBudget,ids=state.selectedChannels;if(!ids.length)return;let used=ids.reduce((n,id)=>n+(state.channelBudgets[id]||0),0);if(used===0){ids.forEach(id=>state.channelBudgets[id]=Math.floor(total/ids.length));used=ids.reduce((n,id)=>n+state.channelBudgets[id],0)}if(used>total){let over=used-total;for(const id of ids){const cut=Math.min(over,state.channelBudgets[id]);state.channelBudgets[id]-=cut;over-=cut;if(over<=0)break}}else if(used<total){state.channelBudgets[ids[0]]+=(total-used)} }
function updateMixCopy(){const goal=state.goal;const selected=state.selectedChannels.map(id=>CHANNELS.find(c=>c.id===id)?.name).filter(Boolean);const advice={拉新:'拉新优先保证“高触达 + 高频短内容”，再用社区或攻略承接。',回流:'回流优先保证存量触达，素材节奏要给用户明确的回来理由。',活跃:'活跃优先保持连续内容和可参与动作，避免整周只有一个峰值。',社区热度:'社区热度优先制造讨论事件，再把反馈转成二次内容。'};const ch=selected.join(' · ')||'未选择';$('mixCopy').textContent=`${advice[goal]} 当前组合：${ch}。`}
function renderCreative(){const arr=ASSETS.slice(0,9);$('creativeGrid').innerHTML=arr.map(a=>`<div class="creative-card" data-creative="${a.id}"><div class="creative-thumb" style="--game-img:url('${imgFor(state.game,a.id+'-creative')}')"></div><div class="creative-meta"><div><small>${a.code}</small><span>${a.cost}R</span></div><b>${a.name}</b><p>${a.desc}</p></div></div>`).join('');document.querySelectorAll('[data-creative]').forEach(c=>c.onclick=()=>openAssetModal(c.dataset.creative))}
function renderIntel(){const arr=INTEL[state.game];$('intelSource').textContent=GAMES[state.game].source; $('intelStrip').innerHTML=arr.map(x=>`<a class="intel-card" href="${x.url}" target="_blank" rel="noopener"><div class="intel-img" style="--game-img:url('${GAMES[state.game].gallery[x.img]}')"></div><div><b>${x.title}</b><span>${x.desc}</span><small>OPEN SOURCE ↗</small></div></a>`).join('')}
function generateBaseline(){state.board=Array.from({length:DAYS},()=>Array(SLOTS).fill(null));let ids=state.goal==='拉新'?['pv','short','kol','guide','short','ugc','push']:state.goal==='回流'?['reward','push','short','guide','reward','community','recap']:state.goal==='活跃'?['short','guide','ugc','live','guide','push','recap']:['pv','ugc','live','community','short','community','recap'];if(state.resource===1)ids=ids.filter((_,i)=>![2,5].includes(i));if(state.resource===3)ids.splice(2,0,'kol');const pos=[[0,1],[0,2],[1,1],[2,1],[3,2],[5,1],[6,1],[4,1],[4,2]];ids.slice(0,pos.length).forEach((id,i)=>{const [d,s]=pos[i];state.board[d][s]=assetById(id)});state.baselineScore=calcScore();renderBoard();refreshOps();toast('基准方案已生成')}
function autoBalance(){const items=flat();if(!items.length)return generateBaseline();const sorted=items.slice().sort((a,b)=>b.weight-a.weight);state.board=Array.from({length:DAYS},()=>Array(SLOTS).fill(null));sorted.forEach((x,i)=>{const candidates=[];for(let d=0;d<DAYS;d++)for(let s=0;s<SLOTS;s++)candidates.push({d,s,load:state.board[d].filter(Boolean).reduce((n,a)=>n+a.weight,0)});candidates.sort((a,b)=>a.load-b.load||a.d-b.d);for(const c of candidates){if(!state.board[c.d][c.s]){state.board[c.d][c.s]=x;break}}});renderBoard();refreshOps();toast('重资产已自动分散')}
function validatePlan(){const issues=getIssues();toast(issues.some(x=>x.level==='bad')?`QA：发现 ${issues.filter(x=>x.level==='bad').length} 个红色冲突`:`QA：${issues.length?`发现 ${issues.length} 个可优化点`:'方案通过'}`);goPage('qa')}
function renderQA(){const c=getScoreComponents(),score=calcScore();$('qaScore').textContent=score;$('qaLabel').textContent=score>=88?'EXECUTION READY':score>=74?'GOOD BASELINE':score>=55?'NEEDS TUNING':'BUILD A PLAN';$('componentBars').innerHTML=Object.entries({GOAL_FIT:c.goal,COVERAGE:c.coverage,CADENCE:c.cadence,CHANNEL:c.channel,RESOURCE:c.resource,BUDGET:c.budget}).map(([k,v])=>`<div class="component-row"><label>${k}</label><div class="track"><i style="width:${Math.round(v)}%"></i></div><b>${Math.round(v)}</b></div>`).join('');const issues=getIssues();$('qaIssues').innerHTML=(issues.length?issues:[{level:'ok',text:'当前没有明显冲突。'}]).map(i=>`<div class="issue-item ${i.level}">${i.text}</div>`).join('');const loads=state.board.map(d=>d.filter(Boolean).reduce((n,x)=>n+x.weight,0));$('loadChart').innerHTML=loads.map((v,i)=>`<div class="load-bar ${v>5?'over':''}"><div class="load-track"><div class="load-fill" style="height:${Math.min(100,v/6*100)}%"></div></div><div class="load-label"><span>D${i+1}</span><b>${v}</b></div></div>`).join('');const a=flat(),used=a.reduce((n,x)=>n+x.cost,0),heavy=a.filter(x=>x.weight===3).length,channels=state.selectedChannels.map(id=>CHANNELS.find(c=>c.id===id).name).join(' · ')||'未选择';$('summaryGrid').innerHTML=[['GAME',GAMES[state.game].name,'当前任务游戏'],['OBJECTIVE',state.goal,'主要运营目标'],['ACTIONS',a.length,'已放置运营动作'],['RESOURCE',`${used}/${RESOURCE_LEVELS[state.resource-1].points}R`,`资源消耗 / 上限`],['HEAVY',heavy,'重资产动作数量'],['CHANNELS',channels,'当前传播渠道'],['ACTIVE DAYS',new Set(state.board.map((d,i)=>d.some(Boolean)?i:null).filter(x=>x!==null)).size,'有动作的天数'],['SCORE',score,'策略评分']].map(x=>`<div class="summary-card"><small>${x[0]}</small><b>${x[1]}</b><p>${x[2]}</p></div>`).join('')}
function openAssetModal(id){const a=assetById(id);if(!a)return;const visual=imgFor(state.game,id+'-modal');$('modalBody').innerHTML=`<div class="modal-visual" style="background-image:linear-gradient(0deg,rgba(4,7,9,.36),transparent 65%),url('${visual}')"></div><div class="modal-kicker">${a.code} · ${a.tag}</div><div class="modal-title">${a.name}</div><div class="modal-body">${a.desc}。这是一个用于模拟发行节奏的运营动作，可被拖拽进 7 日排期并参与资源、负载和策略评分计算。</div><div class="modal-grid"><div class="modal-stat"><small>KIND</small><b>${a.kind}</b></div><div class="modal-stat"><small>LOAD</small><b>${a.weight}</b></div><div class="modal-stat"><small>COST</small><b>${a.cost}R</b></div><div class="modal-stat"><small>ROLE</small><b>${usageText(a)}</b></div></div>`;$('modal').classList.remove('hidden')}
function closeModal(){$('modal').classList.add('hidden')}
function exportCSV(){const rows=[['Game','Node','Goal','Audience','Resource','Day','Slot','Asset','Type','Weight','ResourceCost','Channels','ChannelBudget','StrategyScore']];const ch=state.selectedChannels.map(id=>CHANNELS.find(c=>c.id===id).name).join('|');const cb=state.selectedChannels.map(id=>`${CHANNELS.find(c=>c.id===id).name}:${state.channelBudgets[id]||0}R`).join('|');for(let d=0;d<DAYS;d++)for(let s=0;s<SLOTS;s++){const x=state.board[d][s];if(x)rows.push([GAMES[state.game].name,NODES[state.node][0],state.goal,state.audience,RESOURCE_LEVELS[state.resource-1].name,`Day ${d+1}`,SLOT_NAMES[s],x.name,x.kind,x.weight,x.cost,ch,cb,calcScore()])}const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));a.download='game-release-plan-v9.csv';a.click();URL.revokeObjectURL(a.href);toast('已导出 game-release-plan-v9.csv')}
function refreshOps(){renderBoardMeta();renderInsight();renderChannels();renderCreative();renderIntel();if(state.currentPage==='qa')renderQA()}
function renderAll(){renderHero();renderGames();renderNodes();renderGoals();renderAudience();renderMissionBrief();updateResource();renderBoard();renderChannels();renderCreative();renderIntel();renderInsight();if(state.currentPage==='qa')renderQA()}
function applyPreset(type){if(type==='launch'){state.game='king';state.goal='拉新';state.node=0;state.audience='潜在新用户';state.resource=2}else if(type==='return'){state.game='naruto';state.goal='回流';state.node=2;state.audience='流失玩家';state.resource=2}else{state.game='naruto';state.goal='社区热度';state.node=4;state.audience='核心玩家';state.resource=3}state.channelBudget=70;state.selectedChannels=['douyin','bilibili','community'];state.channelBudgets={douyin:26,bilibili:22,community:22};renderAll();generateBaseline();document.querySelectorAll('.preset').forEach(x=>x.classList.toggle('active',x.dataset.preset===type));goPage('board')}
function resetAll(){Object.assign(state,{game:'king',node:0,goal:'拉新',audience:'潜在新用户',resource:2,channelBudget:70,selectedChannels:['douyin','bilibili','community'],channelBudgets:{douyin:26,bilibili:22,community:22},board:Array.from({length:DAYS},()=>Array(SLOTS).fill(null)),picked:null,baselineScore:0,currentPage:'brief'});renderAll();goPage('brief');toast('已恢复默认状态')}
function setup(){renderAll();initNav();$('resourceRange').oninput=e=>{state.resource=+e.target.value;updateResource();renderInsight();renderBoardMeta()};$('channelBudgetRange').oninput=e=>{state.channelBudget=+e.target.value;rebalanceChannelBudgets();renderChannels();renderInsight()};$('generateBtn').onclick=generateBaseline;$('autoBalance').onclick=autoBalance;$('validateBtn').onclick=validatePlan;$('exportBtn').onclick=exportCSV;$('resetAll').onclick=resetAll;$('modalClose').onclick=closeModal;document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>applyPreset(b.dataset.preset));document.addEventListener('click',e=>{if(e.target.id==='modal')closeModal()})}
setup();
